Mongo db
Anthony271828/HM-DiscordBot pull request #18
Opened 2021-07-30 16:33 UTC by Anthony271828

Implements the wrapper to properly interact with the database.

Implemented Wrapper:
- _Subjects_
- _StudyChannels_
- _GamingChannels_
- Generic wrapper for primitive purposes

Also implemented _CollectionEnum_ to provide all currently used database collections

2021-07-30 19:02 UTC, maxwai requested changes
see comments. I'm leaving it to @Anthony271828 that the methods themselves work

2021-07-30 21:06 UTC, Anthony271828 commented on Mongo/gamingChannels.py
> +class GamingChannel(MongoDocument):
If frozen would be set to True, then the token could not be changed.

2021-07-30 21:07 UTC, Anthony271828 commented on Mongo/studyChannels.py
>  class StudyChannel(MongoDocument):
If frozen would be set to True, then the token could not be changed, for example.

2021-07-30 21:08 UTC, Anthony271828 commented on Mongo/gamingChannels.py
> +        super().__init__(os.environ["DB_NAME"], self.__class__.__name__)
We could do a default, but I would still like to leave the option open.

2021-07-30 21:10 UTC, Anthony271828 commented on Mongo/gamingChannels.py
> +        owner, chat, voice, token, delete_at = entry
This is to leave open the option to set a deadline beyond the default. This should allow for special long term chats if needed.

2021-07-30 21:10 UTC, Anthony271828 commented on Mongo/studyChannels.py
> +        hours = await PrimitiveMongoData.find_configuration(CollectionEnum.ROLES_SETTINGS, "deleteAfter", "HOURS")
Will fix that!

2021-07-30 21:35 UTC, Anthony271828 commented on Mongo/gamingChannels.py
> +            "token": token,
Will also fix that!

2021-07-30 22:08 UTC, Anthony271828 commented on Mongo/subjects.py
>          return self.chat.id
Now that you mention it...

2021-07-30 22:14 UTC, Anthony271828 commented
I hope that your demands have been adequately implemented.

The reason for adding three more enums is to ensure a better distinction regarding the purpose of the strings. Even if the naming is crappy, I hope that the purpose is clear.

2021-07-31 05:55 UTC, maxwai commented on Mongo/gamingChannels.py
> +        super().__init__(os.environ["DB_NAME"], self.__class__.__name__)
Yes then de a default and leave the option open

2021-07-31 06:02 UTC, maxwai requested changes
forgot one thing then it is fine

2021-07-31 06:02 UTC, maxwai commented on Mongo/gamingChannels.py
> +            "token": self.token,
Forgot to add enum values here

2021-07-31 09:23 UTC, Anthony271828 commented
Your change request should be fully done.

2021-08-02 08:46 UTC, maxwai approved these changes

2021-08-02 08:46 UTC, merged